# =====================================================
# ELITE SOC ANALYZER — ENTERPRISE HTML REPORT ENGINE
# AUTHOR: VISHAL - SOC ENGINEERING
# =====================================================

import os
from datetime import datetime
from ui import display_status
from config import REPORT_DIR, TOOL_NAME, TOOL_VERSION, TOOL_AUTHOR

# ==================== HTML REPORT ====================

class HTMLReportGenerator:
    """
    ENTERPRISE-GRADE SOC HTML REPORT
    """

    def __init__(self):
        os.makedirs(REPORT_DIR, exist_ok=True)

    def generate_html(self, alerts, stats, report_id):
        display_status("GENERATING ENTERPRISE HTML REPORT")

        def esc(v):
            return str(v).replace("<", "&lt;").replace(">", "&gt;")

        rows = []
        for alert in alerts:
            rows.append(f"""
            <tr class="{alert.get('THREAT_LEVEL','').lower()}">
                <td>{esc(alert.get('THREAT_LEVEL','N/A'))}</td>
                <td>{esc(alert.get('THREAT_TYPE','UNKNOWN'))}</td>
                <td>{esc(alert.get('SOURCE_IP','N/A'))}</td>
                <td>
                    <div class="risk-bar" style="width:{alert.get('RISK_SCORE',0)}%">
                        {alert.get('RISK_SCORE',0)}
                    </div>
                </td>
                <td>{alert.get('CONFIDENCE',0)}%</td>
                <td>{esc(alert.get('GEO_COUNTRY','UNK'))}</td>
                <td>{esc(alert.get('RECOMMENDED_ACTION','INVESTIGATE'))}</td>
            </tr>
            """)

        rows_html = "\n".join(rows)

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>ELITE SOC REPORT {report_id}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<style>
body {{
    background: linear-gradient(135deg,#0a0e27,#1a1f3a);
    color:#e0e6ed;
    font-family:Segoe UI,system-ui,sans-serif;
    padding:20px;
}}
.container {{
    max-width:1600px;
    margin:auto;
}}
.header {{
    background:linear-gradient(135deg,#1a2332,#2d3748);
    padding:30px;
    border-radius:12px;
    margin-bottom:30px;
}}
h1 {{
    color:#00d4ff;
    text-shadow:0 0 15px rgba(0,212,255,.6);
}}
.stats {{
    display:grid;
    grid-template-columns:repeat(auto-fit,minmax(200px,1fr));
    gap:20px;
    margin-bottom:30px;
}}
.stat {{
    background:#1e293b;
    padding:20px;
    border-radius:10px;
}}
.stat h3 {{
    color:#94a3b8;
    font-size:.9em;
}}
.stat .value {{
    font-size:2em;
    color:#00d4ff;
    font-weight:bold;
}}
table {{
    width:100%;
    border-collapse:collapse;
    background:#1e293b;
    border-radius:10px;
    overflow:hidden;
}}
th {{
    background:#0f172a;
    color:#00d4ff;
    padding:15px;
    text-align:left;
}}
td {{
    padding:12px;
    border-top:1px solid #334155;
}}
tr.critical {{background:rgba(220,38,38,.15);}}
tr.high {{background:rgba(234,88,12,.15);}}
tr.medium {{background:rgba(234,179,8,.15);}}

.risk-bar {{
    height:20px;
    background:linear-gradient(90deg,#10b981,#eab308,#dc2626);
    border-radius:10px;
    color:white;
    text-align:center;
    font-size:.8em;
}}

.footer {{
    margin-top:40px;
    text-align:center;
    color:#64748b;
}}
</style>
</head>

<body>
<div class="container">

<div class="header">
    <h1>🛡️ ELITE SOC ANALYSIS REPORT</h1>
    <p>{TOOL_NAME} v{TOOL_VERSION} — {TOOL_AUTHOR}</p>
    <p>REPORT ID: {report_id}</p>
    <p>GENERATED: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
</div>

<div class="stats">
    <div class="stat"><h3>TOTAL LOG LINES</h3><div class="value">{stats.get('TOTAL_LINES',0)}</div></div>
    <div class="stat"><h3>PARSED EVENTS</h3><div class="value">{stats.get('PARSED_EVENTS',0)}</div></div>
    <div class="stat"><h3>TOTAL THREATS</h3><div class="value">{stats.get('THREATS_DETECTED',0)}</div></div>
    <div class="stat"><h3>CRITICAL</h3><div class="value">{stats.get('CRITICAL_THREATS',0)}</div></div>
    <div class="stat"><h3>HIGH</h3><div class="value">{stats.get('HIGH_THREATS',0)}</div></div>
    <div class="stat"><h3>ML ANOMALIES</h3><div class="value">{stats.get('ML_ANOMALIES_DETECTED',0)}</div></div>
</div>

<h2>🚨 Threat Detections</h2>

<table>
<thead>
<tr>
<th>SEVERITY</th>
<th>THREAT TYPE</th>
<th>SOURCE IP</th>
<th>RISK</th>
<th>CONFIDENCE</th>
<th>COUNTRY</th>
<th>ACTION</th>
</tr>
</thead>
<tbody>
{rows_html}
</tbody>
</table>

<div class="footer">
<p>Enterprise SOC Report • Generated by {TOOL_NAME}</p>
</div>

</div>
</body>
</html>
"""

        file_path = os.path.join(
            REPORT_DIR, f"ELITE_REPORT_{report_id}.html"
        )

        with open(file_path, "w", encoding="utf-8") as f:
            f.write(html)

        display_status(f"HTML REPORT GENERATED: {file_path}")
        return file_path